### ISSUE TITLE
Trying to run a simple demo, flutter_windows.dll not found

### ISSUE THREAD

**Issue by dmondra2** [timsneath/win32_runner#14]
I tried following both the README on github and the installation instruction on pub.dev, didn't have the smoothest of times as I'm new to flutter and dart generally.

Had issues initially trying to dart compile win32_runner into my demo_app, couldn't resolve the package 'args'.

Resolved that by going into the win32_runner project directory and running `dart pub add args` which changed 51 dependencies and alerted me 1 package was discontinued.

Then I was able to dart compile win32_runner into my demo_app root directory. But it's now saying the following:
``C:\src\demo_app>.\win32_runner.exe `flutter_windows.dll` file not found at "C:\src\demo_app\.\windows\flutter\ephemeral\flutter_windows.dll".``

I confirmed that was in fact not there. I was getting sick of fighting with windows cmd so I fired up WSL and the find commands tells me I have flutter_windows.dll in C:\src\flutter\bin\cache\artifacts\engine\windws-x64

So I copied it do the directory in the path relative to my project where it was looking for it, and tried it again.

Window opened for all of a second then everything crashed. I'm now at a loss since I'm not sure why it can't create a view controller:
`C:\src\demo_app>.\win32_runner.exe`
`../../../flutter/shell/platform/embedder/embedder.cc (1828): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary.`
`[ERROR:flutter/shell/platform/windows/flutter_windows_engine.cc(454)] Failed to start Flutter engine: error 2`
`Unhandled exception:`
`Exception: Failed to create view controller.`
`#0      new FlutterEmbedder (package:win32_runner/src/embedder.dart:58)`
`#1      Application.winMain (file:///c:/src/win32_runner/example/win32_runner.dart:113)`
`#2      initApp (package:win32/src/utils.dart:74)`
`#3      main (file:///c:/src/win32_runner/example/win32_runner.dart:14)`
`#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)`
`#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)`
`Failed to shutdown NativeSymbolResolver (SymCleanup  6)`

Flutter version:
`C:\Windows\System32>flutter --version`
`Flutter 3.22.0-14.0.pre.62 • channel master • https://github.com/flutter/flutter.git`
`Framework • revision 28675753ff (4 hours ago) • 2024-04-20 08:25:25 -0400`
`Engine • revision 40110ec82d`
`Tools • Dart 3.5.0 (build 3.5.0-82.0.dev) • DevTools 2.35.0-dev.8`

Windows 10 - 22H2

Any help/guidance is greatly appreciated, thanks in advance!

**Comment by halildurmus** [comment]
I've updated the [usage instructions](https://github.com/halildurmus/win32_runner?tab=readme-ov-file#usage) to make it more clear. Can you try again?

**Comment by dmondra2** [comment]
Worked like a charm!
