### ISSUE TITLE
Multiple flutter instances in one process

### ISSUE THREAD

**Issue by krll-kov** [timsneath/win32_runner#3]
Hi, is it possible to run multiple flutter instances in one process? 

Recently i've asked you this question(https://github.com/timsneath/win32/issues/357) and you advised me to check this https://github.com/ilopX/win, so i went there and author told me that you've implemented this feature here, in this repository.
![image](https://user-images.githubusercontent.com/63228361/153557292-ae5d669d-e28e-4505-9821-228c090f328f.png)

Can you provide an example of how yo do it? (Something like this): 

https://user-images.githubusercontent.com/63228361/153557733-cb477dfb-dc61-416f-bbd3-3bf0158cda30.mp4

When i try to add new instance with this example project(https://github.com/timsneath/win32_runner/blob/main/example/win32_runner.dart), my app freezes with the main window and does no longer respond to any actions

**Comment by timsneath** [comment]
https://pub.dev/packages/nativeshell might be an option for you. It's not something I'm targeting right now.
